export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_SUCCESS";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const SET_PREVIOU_LOCATION = "SET_PREVIOU_LOCATION";
export const SET_AUTHEN = "SET_AUTHEN";
